### ISSUE TITLE
Error "Cannot read properties of undefined (reading '_def')"

### ISSUE THREAD

**Issue by matthiasfeist-foodfacts** [lostfictions/znv#10]
Hi. I am currently executing the example code in the readme and I am getting always an error `Cannot read properties of undefined (reading '_def')`

My versions: 
"znv": "^0.3.2",
"zod": "^3.21.4"

**Comment by lostfictions** [comment]
Hi there, this should be resolved now in `znv@0.4.0`. Please feel free to reopen if it isn't!
