### ISSUE TITLE
Vite's environment variables

### ISSUE THREAD

**Issue by duyth1203** [lostfictions/znv#4]
Hi, I'm using ViteJs to develop React application. I tried adding `znv` then start the app but got the following error:
```
parse-env.ts:176 Uncaught Error: Errors found while parsing environment:
  [DEV]:
    Cannot read properties of undefined (reading '_def')
    (received true)
 ...
```

My usage is as following:
```Typescript
import { z } from 'zod'
import { parseEnv } from 'znv'

export const {  DEV: IS_DEVELOPMENT } = parseEnv(import.meta.env, { DEV: z.boolean().default(true) }
```

Note that instead of `process.env` usually used in CRA, ViteJs uses `import.meta.env` for [environment variables](https://vitejs.dev/guide/env-and-mode.html) which looks like the cause IMO. I tried another project using `process.env` and it works fine.
I read the document and I know the library supports `process.env` but hope to see Vite too.
In case you need to see my ViteJs config
```Typescript
import react from '@vitejs/plugin-react-swc'
import { defineConfig, loadEnv } from 'vite'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig(({ mode }) => {
  // Load env file based on `mode` in the current working directory.
  // Set the third parameter to '' to load all env regardless of the `VITE_` prefix.
  const env = loadEnv(mode, process.cwd(), '')
  return {
    plugins: [react(), tsconfigPaths()],
    optimizeDeps: {
      // https://github.com/vitejs/vite/issues/8069
      include: ['react/jsx-runtime'],
    },
  }
})

```

**Comment by evantill** [comment]
I hade the same error `Cannot read properties of undefined (reading '_def')` without using vite.

But when trying to reproduce the error on. a simpliest project, the error disapear 😢 ...

Can you share your `package.json` ?

**Comment by evantill** [comment]
or just try updating your depencies versions ?

**Comment by BowlingX** [comment]
This is caused by using `modules`, `zod` provides an import map and exports different modules for `es` modules. That means if your project uses `type: "module"`, it will provide the instances of another source file.

This: https://github.com/lostfictions/znv/blob/master/src/parse-env.ts#L121 check here will then fail, because `znv` uses `require` (which resolves to a different `zod` module).

To fix the problem `znv` should provide both `es` modules and `commonjs` modules.
