### ISSUE TITLE
Upgrade zod version

### ISSUE THREAD

**Issue by poko-tin** [lostfictions/znv#5]
Hi. Znv is a good project.

Recently, zod release a new version with support of corece, we do something like:

```ts
z.corece.number()
```

instead of:

```ts
export const numberSchema = z.preprocess((val) => {
  if (typeof val === 'string') return parseInt(val, 10);
  return val;
}, z.number());

numberSchema()
```

would appreciate if you upgrade zod version of znv.

**Comment by lostfictions** [comment]
Hi there, it sounds like there might be a little confusion about what this module is for. I could probably document this better, especially in light of new zod versions that include `coerce`.

_znv already performs coercions_ that are appropriate for use when parsing environment variables. You should generally not need to use `preprocess` _or_ `coerce`, and there's definitely no need to use them for simple schemas like a number schema. znv's whole value proposition is that you do not need to write complex preprocessing schemas for your schemas unless you're doing something really unusual.

I'd invite you to take a look at the first few examples in the README, as well as the section entitled ["What does znv actually do?"](https://github.com/lostfictions/znv#what-does-znv-actually-do).

As for Zod's newer `coerce` functionality, as [noted in Zod's documentation](https://github.com/colinhacks/zod#coercion-for-primitives), it has some surprising behaviours. For example, `false`, `no`, `123`, and `dogs` all coerce to `true` when using the `z.coerce.boolean()` schema. This means Zod's coercions are often inappropriate for use in environment variable parsing, where all input values are strings. By contrast, znv tries to perform coercions that are slightly opinionated, well-documented, and appropriate for the problem domain. Again, I'd invite you to read the section in the README entitled ["Coercion rules"](https://github.com/lostfictions/znv#coercion-rules) to learn more.

I'll leave this issue open as a reminder to add better documentation about `coerce` to the README. I may also add a section called something like "you might not need znv" -- there's already a callout under the [Usage section](https://github.com/lostfictions/znv#usage) about not using znv for general-purpose validation, but it might make sense to make the warning even more prominent.

Let me know if you still have any questions!

**Comment by poko-tin** [comment]
Thank you! I have problem with `znv` seems to be forcing the project to use the old zod, think that I should research a way to use the new zod version by modify `package.json` instead 👍
